# Generated by Django 6.0.7 on 2026-07-10 11:26

from django.db import migrations


def bootstrap_membership(apps, schema_editor):
    ChatRoom = apps.get_model('myapp', 'ChatRoom')
    User = apps.get_model('auth', 'User')
    all_users = list(User.objects.all())
    for room in ChatRoom.objects.all():
        room.members.add(*all_users)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_chatroom_members_roominvite_notification'),
    ]

    operations = [
        migrations.RunPython(bootstrap_membership, noop_reverse),
    ]
